=== the-gomps/gomps-game-configs/gomps-settings-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "description": "JSON Schema",
      "type": "string"
    },
    "BaseScale": {
      "description": "Base scale multiplier for everything Gomps creates. Bigger number, bigger gomp.",
      "type": "number",
      "default": 1
    },
    "LocalPlayer": {
      "description": "",
      "$ref": "#/definitions/ObjectSearch"
    },
    "MainCamera": {
      "description": "",
      "$ref": "#/definitions/ObjectSearch"
    },
    "Origin": {
      "description": "",
      "$ref": "#/definitions/ObjectSearch"
    },
    "Text": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "TextScale": {
          "type": "number",
          "description": ""
        },
        "FontName": {
          "type": "string",
          "description": ""
        },
        "PreferUiText": {
          "type": "boolean",
          "description": ""
        }
      }
    },
    "RemotePlayer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "PositionOffset": {
          "type": "string",
          "description": ""
        },
        "EulerAnglesOffset": {
          "type": "string",
          "description": ""
        }
      }
    },
    "Rendering": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ShaderName": {
          "type": "string",
          "description": ""
        },
        "RenderQueue": {
          "type": "number",
          "description": ""
        }
      }
    }
  },
  "definitions": {
    "SearchQuery": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Component": {
          "type": "string",
          "description": "Name of a Component / MonoBehaviour, including the namespace. Most games don't use a namespace for their custom scripts, but many do, so make sure you're using the correct full name. Example: 'UnityEngine.CharacterController'"
        },
        "Tag": {
          "type": "string",
          "description": "Object tag to search for. Common tags are Player and MainCamera (which Gomps already uses by default to find the main camera and player object)."
        },
        "ObjectName": {
          "type": "string",
          "description": "Case insensitive game object name to search for."
        },
        "ChildPath": {
          "type": "string",
          "description": "After a base object is found using any combination of Component, Tag and ObjectName, this path is used to find a more specific child. This is useful in cases where the game's player object represents the entire character body, and you want the gomp to be specifically in the character's head, for instance. Format: 'ChildA/ChildB/ChildC'."
        }
      }
    },
    "ObjectSearch": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Include": {
          "type": "array",
          "description": "",
          "items": {
            "$ref": "#/definitions/SearchQuery"
          }
        },
        "Exclude": {
          "type": "array",
          "description": "",
          "items": {
            "$ref": "#/definitions/SearchQuery"
          }
        }
      }
    }
  }
}

=== the-gomps/gomps-game-configs/games/wizardoflegend.json
{
  "$schema": "https://the-gomps.github.io/gomps-game-settings/gomps-settings-schema.json",
  "BaseScale": 2,
  "LocalPlayer": {
    "Include": [
      {
        "ObjectName": "Player0",
        "ChildPath": "PlayerSprite/HeadPosition"
      }
    ]
  },
  "Text": {
    "TextScale": 1.5
  },
  "RemotePlayer": {
    "EulerAnglesOffset": "0,130,0"
  }
}

=== the-gomps/gomps-game-configs/games/140.json
{
  "$schema": "https://the-gomps.github.io/gomps-game-settings/gomps-settings-schema.json",
  "BaseScale": 2,
  "LocalPlayer": {
    "Include": [
      {
        "ObjectName": "Player"
      }
    ]
  },
  "Text": {
    "TextScale": 1.5
  },
  "RemotePlayer": {
    "EulerAnglesOffset": "0,180,0"
  }
}

=== the-gomps/gomps-game-configs/games/ashorthike.json
{
  "$schema": "https://the-gomps.github.io/gomps-game-settings/gomps-settings-schema.json",
  "LocalPlayer": {
    "Include": [
      {
        "Tag": "Player",
        "ChildPath": "Character/Armature/root/Base/Chest/Head"
      }
    ]
  },
  "RemotePlayer": {
    "EulerAnglesOffset": "0,0,90"
  },
  "BaseScale": 5,
  "Text": {
    "TextScale": 2
  }
}

=== the-gomps/gomps-game-configs/v2/games/id2.json
{
  "$schema": "https://the-gomps.github.io/gomps-game-settings/gomps-settings-schema.json",
  "BaseScale": 1,
  "LocalPlayer": {
    "Include": [
      {
        "ObjectName": "PlayerEnt",
        "ChildPath": "Ittle/ittle/Armature/root/chest/head"
      }
    ]
  },
  "Text": {
    "TextScale": 2
  },
  "RemotePlayer": {
    "EulerAnglesOffset": "0,0,90"
  }
}

=== the-gomps/gomps-game-configs/games/elseheartbreak.json
{
  "$schema": "https://the-gomps.github.io/gomps-game-settings/gomps-settings-schema.json",
  "BaseScale": 1.5,
  "LocalPlayer": {
    "Include": [
      {
        "Component": "CharacterShell",
        "ObjectName": "Sebastian",
        "ChildPath": "Sebastian_Ny/CharacterRig/master_ctrl/root_bn/spine0_bn/spine1_bn/shoulder_bn/head_bn"
      }
    ]
  },
  "Text": {
    "TextScale": 1.5
  },
  "RemotePlayer": {
    "EulerAnglesOffset": "90,0,90"
  }
}

=== the-gomps/gomps-game-configs/games/gris.json
{
  "$schema": "https://the-gomps.github.io/gomps-game-settings/gomps-settings-schema.json",
  "BaseScale": 1,
  "LocalPlayer": {
    "Include": [
      {
        "Component": "Gris.CharacterController2D",
        "ChildPath": "Sprite"
      }
    ]
  },
  "MainCamera": {
    "Include": [
      {
        "ObjectName": "Main Camera(Clone)"
      }
    ]
  },
  "Text": {
    "TextScale": 2
  },
  "RemotePlayer": {
    "PositionOffset": "0,0.9,0",
    "EulerAnglesOffset": "0,130,0"
  }
}

=== the-gomps/gomps-game-configs/games/hollow-knight.json
{
  "$schema": "https://the-gomps.github.io/gomps-game-settings/gomps-settings-schema.json",
  "BaseScale": 2,
  "LocalPlayer": {
    "Include": [
      {
        "ObjectName": "Knight"
      }
    ]
  },
  "Text": {
    "TextScale": 3
  },
  "RemotePlayer": {
    "PositionOffset": "0.0,-0.6,0.0",
    "EulerAnglesOffset": "0.0,180,0.0"
  }
}

=== the-gomps/gomps-game-configs/v2/games/elseheartbreak.json
{
  "$schema": "../gomps-settings-schema.json",
  "BaseScale": 1.5,
  "LocalPlayer": {
    "Include": [
      {
        "Component": "CharacterShell",
        "ObjectName": "Sebastian",
        "ChildPath": "Sebastian_Ny/CharacterRig/master_ctrl/root_bn/spine0_bn/spine1_bn/shoulder_bn/head_bn"
      }
    ]
  },
  "Text": {
    "TextScale": 2
  },
  "RemotePlayer": {
    "EulerAnglesOffset": "90,0,90"
  }
}
